[workspace]
resolver = "2"

members = [
    "alchemix-rx",
    "alchemix-web",
    "alchemix-utils",
    "alchemix-entity-macros",
    "alchemix-rx-macros"
]

[workspace.package]
name = "alchemix"
version = "0.1.0"
