[package]
name = "alchemix-entity-macros"
version.workspace = true
edition = "2021"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true