[package]
name = "alchemix_utils"
version = "0.1.0"
edition = "2021"

[lib]
name= "alchemix_utils"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1"

uuid = { version = "1.11.0", features = ["v4"] }

chrono = "^0.4"
walkdir = "2"
url = "2.5"
